server:
  port: 8080


# h2 db
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:./data

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


springdoc:
  packages-to-scan: com.gritstandard.project.biz.controller
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    #try it out ? request duration ? ????.
    display-request-duration: true
